apiVersion: v1
kind: Secret
metadata:
  name: civicfix-grafana-secret
  labels:
    civicfix.io/environment: student
stringData:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "replace-with-grafana-admin-password"
