apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: civicfix-monitoring

resources:
  - ../../monitoring

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: civicfix
  - path: prometheus-config-patch.yaml
    target:
      kind: ConfigMap
      name: civicfix-prometheus-config
  - path: prometheus-service-patch.yaml
    target:
      kind: Service
      name: civicfix-prometheus
  - path: grafana-service-patch.yaml
    target:
      kind: Service
      name: civicfix-grafana
  - path: grafana-secret-patch.yaml
    target:
      kind: Secret
      name: civicfix-grafana-secret
