apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - namespace.yaml
  - https://github.com/external-secrets/external-secrets/releases/download/v0.16.2/external-secrets.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: external-secrets-cert-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: external-secrets-cert-controller
      spec:
        template:
          spec:
            containers:
              - name: cert-controller
                args:
                  - --crd-requeue-interval=5m
                  - --service-name=external-secrets-webhook
                  - --service-namespace=external-secrets
                  - --secret-name=external-secrets-webhook
                  - --secret-namespace=external-secrets
                  - --metrics-addr=:8080
                  - --healthz-addr=:8081
                  - --loglevel=info
                  - --zap-time-encoding=epoch
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: external-secrets-webhook
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: external-secrets-webhook
      spec:
        template:
          spec:
            containers:
              - name: webhook
                args:
                  - --port=10250
                  - --dns-name=external-secrets-webhook.external-secrets.svc
                  - --cert-dir=/tmp/certs
                  - --check-interval=5m
                  - --metrics-addr=:8080
                  - --healthz-addr=:8081
                  - --loglevel=info
                  - --zap-time-encoding=epoch
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: externalsecret-validate
    patch: |-
      - op: replace
        path: /webhooks/0/clientConfig/service/namespace
        value: external-secrets
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: secretstore-validate
    patch: |-
      - op: replace
        path: /webhooks/0/clientConfig/service/namespace
        value: external-secrets
      - op: replace
        path: /webhooks/1/clientConfig/service/namespace
        value: external-secrets
