apiVersion: v1
kind: Service
metadata:
  name: civicfix-postgres
  labels:
    app.kubernetes.io/name: civicfix-postgres
    app.kubernetes.io/part-of: civicfix-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: civicfix-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: civicfix-postgres
  labels:
    app.kubernetes.io/name: civicfix-postgres
    app.kubernetes.io/part-of: civicfix-platform
spec:
  serviceName: civicfix-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: civicfix-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: civicfix-postgres
        app.kubernetes.io/part-of: civicfix-platform
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: civicfix-app-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: civicfix-app-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: civicfix-app-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - civicfix_user
                - -d
                - civicfix
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - civicfix_user
                - -d
                - civicfix
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: postgres-init
          configMap:
            name: civicfix-postgres-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
