apiVersion: v1
kind: Secret
metadata:
  name: civicfix-app-secret
  labels:
    app.kubernetes.io/name: civicfix-platform
    app.kubernetes.io/part-of: civicfix-platform
type: Opaque
stringData:
  POSTGRES_PASSWORD: "civicfix_password"
  DATABASE_URL: "postgres://civicfix_user:civicfix_password@civicfix-postgres:5432/civicfix"

