apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: civicfix

resources:
  - namespace.yaml
  - prometheus.yaml
  - grafana.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: civicfix-platform

configMapGenerator:
  - name: civicfix-grafana-datasources
    files:
      - datasources.yaml=grafana-provisioning/datasources.yaml
    options:
      labels:
        app.kubernetes.io/name: civicfix-grafana

  - name: civicfix-grafana-dashboard-providers
    files:
      - dashboards.yaml=grafana-provisioning/dashboards.yaml
    options:
      labels:
        app.kubernetes.io/name: civicfix-grafana

  - name: civicfix-grafana-dashboards
    files:
      - civicfix-overview.json=grafana-dashboards/civicfix-overview.json
    options:
      labels:
        app.kubernetes.io/name: civicfix-grafana
