/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-container": "#edeef0",
        "surface-bright": "#f8f9fb",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ffa929",
        "on-secondary": "#ffffff",
        "tertiary-container": "#6b4200",
        "primary-container": "#1e40af",
        "background": "#f8f9fb",
        "primary": "#00288e",
        "outline-variant": "#c4c5d5",
        "surface-variant": "#e1e2e4",
        "secondary-fixed-dim": "#4edea3",
        "surface-dim": "#d9dadc",
        "primary-fixed-dim": "#b8c4ff",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        "on-surface-variant": "#444653",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed": "#001453",
        "on-secondary-container": "#00714d",
        "surface-container-highest": "#e1e2e4",
        "on-primary-container": "#a8b8ff",
        "on-error-container": "#93000a",
        "inverse-primary": "#b8c4ff",
        "surface-container-low": "#f3f4f6",
        "secondary": "#006c49",
        "outline": "#757684",
        "on-primary-fixed-variant": "#173bab",
        "surface": "#f8f9fb",
        "on-tertiary": "#ffffff",
        "surface-tint": "#3755c3",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-fixed": "#002113",
        "on-tertiary-fixed": "#2a1700",
        "primary-fixed": "#dde1ff",
        "inverse-surface": "#2e3132",
        "secondary-container": "#6cf8bb",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffddb8",
        "inverse-on-surface": "#f0f1f3",
        "tertiary": "#4c2e00",
        "surface-container-high": "#e7e8ea",
        "secondary-fixed": "#6ffbbe"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "lg": "24px",
        "xs": "4px",
        "xl": "32px",
        "container-margin": "20px",
        "base": "8px",
        "sm": "8px",
        "gutter": "16px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
