apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: civicfix-grafana-secret
  namespace: civicfix
  labels:
    app.kubernetes.io/name: civicfix-grafana
    app.kubernetes.io/part-of: civicfix-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: civicfix-azure-key-vault
    kind: ClusterSecretStore
  target:
    name: civicfix-grafana-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: civicfix-grafana-admin-user
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: civicfix-grafana-admin-password
