apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: civicfix-app-secret
  namespace: civicfix-prod
  labels:
    app.kubernetes.io/name: civicfix-platform
    app.kubernetes.io/part-of: civicfix-platform
    civicfix.io/environment: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: civicfix-azure-key-vault
    kind: ClusterSecretStore
  target:
    name: civicfix-app-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: civicfix-prod-postgres-password
    - secretKey: DATABASE_URL
      remoteRef:
        key: civicfix-prod-database-url
    - secretKey: AZURE_STORAGE_CONNECTION_STRING
      remoteRef:
        key: civicfix-prod-storage-connection-string
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: civicfix-prod-openai-api-key
