apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: civicfix-azure-key-vault
  labels:
    app.kubernetes.io/name: civicfix-azure-key-vault
    app.kubernetes.io/part-of: civicfix-platform
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://kv-civicfix-prod-18j6j6.vault.azure.net/
      tenantId: 84f58ce9-43c8-4932-b908-591a8a3007d3
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
