apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: civicfix-azure-key-vault
  labels:
    app.kubernetes.io/name: civicfix-azure-key-vault
    app.kubernetes.io/part-of: civicfix-platform
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://civicfix-kv-placeholder.vault.azure.net/
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
