apiVersion: v1
kind: ConfigMap
metadata:
  name: civicfix-app-config
  labels:
    civicfix.io/environment: prod
data:
  NODE_ENV: "production"
  CORS_ORIGIN: "https://e-document.tech"
  VITE_API_BASE_URL: ""
