apiVersion: apps/v1
kind: Deployment
metadata:
  name: civicfix-frontend
  labels:
    civicfix.io/environment: prod
spec:
  replicas: 3
  template:
    metadata:
      labels:
        civicfix.io/environment: prod
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 600m
              memory: 512Mi
