apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: civicfix-frontend
  labels:
    app.kubernetes.io/name: civicfix-frontend
    app.kubernetes.io/part-of: civicfix-platform
    civicfix.io/environment: prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - civicfix.tech
      secretName: civicfix-prod-frontend-tls
  rules:
    - host: civicfix.tech
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: civicfix-backend
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: civicfix-frontend
                port:
                  name: http
