apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: civicfix-prod

resources:
  - ../../base
  - certificate.yaml
  - ingress.yaml

images:
  - name: ghcr.io/mr-sakit/civicfix-backend
    newTag: a6fdd0eb2e5defda77a72dfc0f86cd3de174c716
  - name: ghcr.io/mr-sakit/civicfix-frontend
    newTag: a6fdd0eb2e5defda77a72dfc0f86cd3de174c716

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: civicfix
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: civicfix-app-config
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: civicfix-backend
  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: civicfix-frontend
  - path: postgres-patch.yaml
    target:
      kind: StatefulSet
      name: civicfix-postgres
