apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: civicfix-prod

resources:
  - ../../base
  - certificate.yaml
  - ingress.yaml
  - hpa.yaml

images:
  - name: ghcr.io/mr-sakit/civicfix-backend
    digest: sha256:a39ee224eaecd6fa6e0323fb0252ce5ace4f9a6321a1d129047b59ab387c9df0
  - name: ghcr.io/mr-sakit/civicfix-frontend
    digest: sha256:8a25a62bdca224a9adde01fe7cf22fa92aeb0ac7577a965e75515e22cfa586a5

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: civicfix
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: civicfix-app-config
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: civicfix-backend
  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: civicfix-frontend
  - path: remove-in-cluster-postgres.yaml
