apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: civicfix-prod

resources:
  - ../../base
  - certificate.yaml
  - ingress.yaml
  - hpa.yaml

images:
  - name: ghcr.io/mr-sakit/civicfix-backend
    digest: sha256:1997da30372869d68a30e90627493caf50fc61bb1b0a36c4185c47dadfb4638e
  - name: ghcr.io/mr-sakit/civicfix-frontend
    digest: sha256:6ac0817540bb781871d709bf59e7d2d39574cb8355cb7e892080a3e7e61d7b8e

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: civicfix
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: civicfix-app-config
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: civicfix-backend
  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: civicfix-frontend
  - path: remove-in-cluster-postgres.yaml
