apiVersion: v1
kind: Namespace
metadata:
  name: civicfix-prod
  labels:
    app.kubernetes.io/name: civicfix-platform
    app.kubernetes.io/part-of: civicfix-platform
    civicfix.io/environment: prod
