ALTER TABLE civic_issues
  ADD COLUMN IF NOT EXISTS ai_status VARCHAR(40) NOT NULL DEFAULT 'not_requested',
  ADD COLUMN IF NOT EXISTS ai_category VARCHAR(100),
  ADD COLUMN IF NOT EXISTS ai_severity VARCHAR(40),
  ADD COLUMN IF NOT EXISTS ai_confidence NUMERIC(5, 4),
  ADD COLUMN IF NOT EXISTS ai_summary TEXT,
  ADD COLUMN IF NOT EXISTS ai_processed_at TIMESTAMPTZ;
