apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: civicfix-student-application
  namespace: argocd
  labels:
    app.kubernetes.io/name: civicfix-student-application
    app.kubernetes.io/part-of: civicfix-platform
    civicfix.io/environment: student
spec:
  project: civicfix-platform
  source:
    repoURL: https://github.com/Mr-Sakit/civicfix-platform.git
    targetRevision: main
    path: deploy/kubernetes/overlays/aks-student
  destination:
    server: https://kubernetes.default.svc
    namespace: civicfix-student
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
