apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - civicfix-external-secrets-operator.yaml
  - civicfix-kyverno.yaml
  - civicfix-kyverno-policies.yaml
  - civicfix-prod-secrets.yaml
  - civicfix-prod-application.yaml
  - civicfix-monitoring.yaml
