apiVersion: apps/v1
kind: Deployment
metadata:
  name: civicfix-backend
  labels:
    civicfix.io/environment: student
spec:
  replicas: 1
  template:
    metadata:
      labels:
        civicfix.io/environment: student
    spec:
      containers:
        - name: backend
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 384Mi
